const WORD_BANK = [
  "ROBÔ","DRAGÃO","PONTE","CASTELO","FOGUETE","PIRATA","VULCÃO","LOBO","ESPADA","ESCUDO",
  "TORRE","RIO","MONTANHA","DESERTO","FLORESTA","OCEANO","ILHA","TEMPESTADE","RAIO","NUVEM",
  "ESTRELA","LUA","SOL","PLANETA","COMETA","GALÁXIA","ASTRONAUTA","NAVE","ALIENÍGENA","LASER",
  "CAVALO","LEÃO","TIGRE","URSO","ÁGUIA","COBRA","TUBARÃO","BALEIA","POLVO","MORCEGO",
  "CASTOR","RAPOSA","CORUJA","FALCÃO","PINGUIM","CANGURU","ELEFANTE","GIRAFA","ZEBRA","RINOCERONTE",
  "VIOLÃO","PIANO","TAMBOR","FLAUTA","GUITARRA","MICROFONE","FONE","RÁDIO","TELEVISÃO","CÂMERA",
  "LIVRO","CANETA","LÁPIS","PAPEL","MAPA","CHAVE","RELÓGIO","ESPELHO","LANTERNA","VELA",
  "PONTO","LINHA","CÍRCULO","TRIÂNGULO","QUADRADO","CUBO","PIRÂMIDE","LABIRINTO","PORTA","JANELA",
  "CARRO","TREM","AVIÃO","BARCO","BICICLETA","MOTO","CAMINHÃO","METRÔ","ÔNIBUS","SUBMARINO",
  "ESTRADA","TÚNEL","AEROPORTO","ESTAÇÃO","PORTO","FÁBRICA","USINA","MERCADO","BANCO","HOTEL",
  "REI","RAINHA","PRÍNCIPE","BRUXA","FANTASMA","VAMPIRO","ZUMBI","MÚMIA","FADA","GIGANTE",
  "ANEL","COROA","MOEDA","TESOURO","BAÚ","BÚSSOLA","CORDA","REDE","ÂNCORA","MASCARA",
  "FOGO","GELO","ÁGUA","AR","TERRA","AREIA","PEDRA","MADEIRA","METAL","VIDRO",
  "QUEIJO","PÃO","MAÇÃ","BANANA","LARANJA","UVA","MORANGO","ABACAXI","MELANCIA","LIMÃO",
  "FUTEBOL","BASQUETE","TÊNIS","XADREZ","DADO","CARTA","BOLA","MEDALHA","TROFÉU","APITO",
  "HOSPITAL","ESCOLA","IGREJA","MUSEU","TEATRO","CINEMA","BIBLIOTECA","PRISÃO","FAROL","MOINHO",
  "VULCÃO","GEISER","CACHOEIRA","LAGOA","PÂNTANO","GRUTA","CAVERNA","RECIFE","DUNA","GLACIAR",
  "COMPUTADOR","TECLADO","IMPRESSORA","SATÉLITE","ANTENA","BATERIA","ÍMÃ","ENGRENAGEM","PARAFUSO","MARTELO",
  "SERROTE","MACHADO","FACA","GARFO","COLHER","PANELA","FORNO","GELADEIRA","LIQUIDIFICADOR","MICRO-ONDAS",
  "CADEIRA","MESA","SOFÁ","CAMA","ARMÁRIO","ESTANTE","TAPETE","CORTINA","LUMINÁRIA","VENTILADOR",
  "CAMISA","CALÇA","SAPATO","CHAPÉU","LUVA","CACHECOL","CINTO","BOLSA","ÓCULOS","RELÓGIO",
  "PALHAÇO","MÁGICO","ACROBATA","MALABARISTA","CIRCO","CARROSSEL","MONTANHA-RUSSA","PALCO","CORTINA","INGRESSO",
  "PROFESSOR","MÉDICO","BOMBEIRO","POLICIAL","PILOTO","MARINHEIRO","AGRICULTOR","PADEIRO","ALFAIATE","FERREIRO"
];

module.exports = WORD_BANK;
